AWS_ACCESS_KEY="AKIAXGTTWUTMJYHSBU5I"
AWS_SECRET_KEY="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"
AWS_REGION="us-east-1"
DATABASE_NAME= "wordpressdb"
USERNAME= "wordpressuser"
DATABASE_PASSWORD= "W3lcome123"
#SNAPSHOT_NAME= "clixxdbsnap"




